services:
  app:
    image: 'node:18-alpine'
    command: 'sh -c "npm install && npm run build && npx serve dist -p 3000"'
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - 'app-data:/app'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - 'http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    working_dir: /app

volumes:
  app-data:
